"""empty message

Revision ID: 3657fa12539f
Revises: d6b14f755e09
Create Date: 2021-03-15 16:52:40.756082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3657fa12539f'
down_revision = 'd6b14f755e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('requester', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_artist'), 'request', ['artist'], unique=False)
    op.create_index(op.f('ix_request_requester'), 'request', ['requester'], unique=False)
    op.create_index(op.f('ix_request_title'), 'request', ['title'], unique=False)
    op.drop_index('ix_video_title', table_name='video')
    op.create_index(op.f('ix_video_title'), 'video', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_title'), table_name='video')
    op.create_index('ix_video_title', 'video', ['title'], unique=1)
    op.drop_index(op.f('ix_request_title'), table_name='request')
    op.drop_index(op.f('ix_request_requester'), table_name='request')
    op.drop_index(op.f('ix_request_artist'), table_name='request')
    op.drop_table('request')
    # ### end Alembic commands ###
