"""empty message

Revision ID: 8ead33bd939c
Revises: 
Create Date: 2021-03-15 19:35:22.787015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ead33bd939c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('requester', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_artist'), 'request', ['artist'], unique=False)
    op.create_index(op.f('ix_request_requester'), 'request', ['requester'], unique=False)
    op.create_index(op.f('ix_request_title'), 'request', ['title'], unique=False)
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_title'), 'video', ['title'], unique=False)
    op.create_index(op.f('ix_video_video_id'), 'video', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_video_id'), table_name='video')
    op.drop_index(op.f('ix_video_title'), table_name='video')
    op.drop_table('video')
    op.drop_index(op.f('ix_request_title'), table_name='request')
    op.drop_index(op.f('ix_request_requester'), table_name='request')
    op.drop_index(op.f('ix_request_artist'), table_name='request')
    op.drop_table('request')
    # ### end Alembic commands ###
